### ISSUE TITLE
Problem in ios zafari

### ISSUE THREAD

**Issue by abelperezlindo** [wolffe/tail.select.js#13]
problem typing an option in the label field on iphone xr zafari. 
I can only type two characters and the search crashes.

**Comment by wolffe** [comment]
Did you find any solution? I don't think legacy browsers are supported, though.

**Comment by abelperezlindo** [comment]
No encontre una solucion, solo ignoro los dispositivos ios. funciona para mi.gracias por trabajar en esto, tails es bonito.  
I did not find a solution, I just ignore ios devices. works for me. thanks for working on this, tail is nice.
```
document.addEventListener("DOMContentLoaded", () => {
  if(isIOSDevice()) return;
  tail.select("#", { ... });
});

function isIOSDevice(){
  return /ipad|iphone|ipod/i.test(navigator.userAgent.toLowerCase());
}

```

**Comment by wolffe** [comment]
You're welcome and feel free to contribute if you have any ideas or improvements.
