### ISSUE TITLE
Translation: DE_de

### ISSUE THREAD

**Issue by panvid** [wolffe/tail.select.js#17]
### All
-   Alle
### None
-   Keine
### Select All
-   Alle auswählen
### Unselect All
-   Alle abwählen
### No Options available
-   Keine Optionen verfügbar
### No Options found
-   Keine Optionen gefunden
### You can't select more Options
-   Es können nicht mehr Optionen ausgewählt werden
### Select an Option...
-   Wähle eine Option...
### Select up to :limit Options...
-   Wähle bis zu :limit Optionen...
### Type in to search...
-   Suchwort eingeben...
### This Field is disabled
-   Dieses Feld ist deaktiviert

**Comment by wolffe** [comment]
Hi @panvid - there is already a German translation. Is it wrong?

**Comment by panvid** [comment]
I did not see it, sorry.

**Comment by wolffe** [comment]
No problem. Sorry it took so long to reply to this ticket.
