### ISSUE TITLE
Cannot import - there are no exports

### ISSUE THREAD

**Issue by TivoSoho** [wolffe/tail.select.js#37]
Cannot use - I have no way to import it and local variables are not available - they are local.

**Comment by wolffe** [comment]
You're not supposed to import it.

Download it and load it from your application, or load it directly from the CDN.

Use <script> tags or any other method available in your application or CMS.

**Comment by TivoSoho** [comment]
Unfortunately not everything can be loaded via CDN. Our application is such that all JS is bundled together. Nowadays many applications no longer use CommonJS and we are one of those - only modules. And unfortunately due to its syntax, it also doesn't work when using a commonJS converter plugin to be able to use "require".

Basically what is missing is just "export default tail;" at the end of the file to be able to import it.
