### ISSUE TITLE
Cannot choose empty option

### ISSUE THREAD

**Issue by TivoSoho** [wolffe/tail.select.js#40]
See example here: https://jsfiddle.net/9nv3btga/1/

Empty options do not have proper height and they cannot be selected. Icon is also off in its position due to lack of proper height

**Comment by wolffe** [comment]
That is true. I have fixed this in my project by making sure I have no empty options.

I cannot help as I don't know the specifications of your project.

**Comment by TivoSoho** [comment]
Actually, I think this point is moot since empty option did work in my tests until I finally managed to emulate it. And now I have discovered it was on old 0.5 branch :D (tail.select instead of tail.select.js) So should not be an issue.
