### ISSUE TITLE
Items within an array of objects do not work in options

### ISSUE THREAD

**Issue by zahovicS** [wolffe/tail.select.js#48]
```
// users array
const users = [
    {
        "key": "cashier test",
        "value": 3
    }
]

```
```
tail.select(".select-users", {
        multiple: true,
        animate: true,
        multiTags: false,
        multiCounter: false,
        theme: 'light',
        classNames: "w-100",
        items: users,
 })
```
 
 version: 1.0.2

**Comment by wolffe** [comment]
You need to create the `<select>` element first.

You can use either JavaScript, or any server-side language you are familiar with.

**Comment by zahovicS** [comment]
Yes, that's what I did, I created an empty select but it still doesn't work, I had to make a query and construct the `<option>` to put them inside the selects and then start **tail**

**Comment by wolffe** [comment]
First you build the `<select>` element, then you trigger `tail()`.
